# Generated by Django 4.0.1 on 2022-01-25 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('result', models.CharField(choices=[('POS', 'مبتلا به گوید 19'), ('NEG', 'عدم ابتلا به کوید 19'), ('TBD', 'نا مشخص')], default='TBD', max_length=50)),
                ('probability', models.FloatField(blank=True)),
                ('visible_to_public', models.BooleanField(default=True)),
                ('visible_to_users', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
