# Generated by Django 4.0.1 on 2022-02-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_sample_issued_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='probability',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
