# Generated by Django 4.0.1 on 2022-02-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_alter_sample_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='predicted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
