# Generated by Django 4.0.1 on 2022-02-08 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=150)),
                ('action_type', models.CharField(choices=[('AUTH', 'Authentication action type'), ('CREATE', 'create object in the db'), ('READ', 'read object in the db'), ('UPDATE', 'update object in the db'), ('DELETE', 'delete object in the db'), ('PREDICT', 'use the COVID prediction api')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
