# Generated by Django 4.0.1 on 2022-02-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_remove_log_failure_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='action_type',
            field=models.CharField(choices=[('AUTH', 'Authentication action type'), ('CREATE', 'create object in the db'), ('READ', 'read object in the db'), ('UPDATE', 'update object in the db'), ('DELETE', 'delete object in the db'), ('PREDICT', 'use the COVID prediction api')], default='READ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
